### ISSUE TITLE
Setup a seed command in django to bootstrap database

### ISSUE THREAD

**Issue by chrichri17** [YacineSteeve/quizoot#22]
## Goal

Setup a seed command using django management. It might looks like `python3 manage.py seed [other_args_to_define]`. 

The seed fonction should read json files from`backend/data` and make the appropriate mongodb queries to populate the database.

We can also achieve this by using another strategy if you prefer, but we might want to discuss this together.

## Todo list
- [x] generate some examples and store them in `backend/data`
- [x] create a seed command that reads those files and insert the data in mongodb
- [x] the seed command might be used to clean the database as well (or we can instead create another command with some name that does both: seed and clean)

__Priority__: LOW
